### ISSUE TITLE
Syntax error on xaseco start

### ISSUE THREAD

**Issue by NoTimeToDrive** [askuri/dynmaps#9] opened 2019-09-29 12:34 UTC
I get this error.
Changed the line inside plugin list a couple times
of course above the RASP files as you said.
```
[XAseco] Load plugin [plugin.checkpoints.php]
[XAseco] Load plugin [plugin.dedimania.php]
[XAseco] Load plugin [askuri.dynmaps.php]  error after here :(

[XAseco] Load plugin [chat.server.php]
[XAseco] Load plugin [chat.songmod.php]
[XAseco] Load plugin [chat.me.php]
[XAseco] Load plugin [askuri.dynmaps.php] error after here :(

[XAseco] Load plugin [plugin.track.php]
[XAseco] Load plugin [plugin.checkpoints.php]
[XAseco] Load plugin [askuri.dynmaps.php] error after here :(

PHP Parse error: syntax error, unexpected '[' in D:\TMFserver\TMF\control\xaseco_1\plugins\askuri.dynmaps.php on line 88
Press a key to continue ...
```

BUT....Maybe this the problem?
I'm running the server on a Windows 7 64bit machine!
Can this cause the error?

I'm no programmer...more a small noob on those things ;-)

Greetings

**Comment by dassschaf** [comment] 2019-09-29 13:15
Make sure you replaced the `rasp.funcs.php` and `plugin.rasp_jukebox.php` files with the ones from this repository and that you put the `<plugin>askuri.dynmaps.php</plugin>` line in the `plugins.xml` file right above the block of RASP plugins - in my case it's below the `<plugin>plugin.checkpoints.php</plugin>` line, however, I don't have the dedimania plugin active there.

Windows is not the problem, I'm working on this under Windows 10 with XAMPP and it's all working fine.

**Comment by askuri** [comment] 2019-09-29 15:20
The problem is most likely your PHP version. We use a language syntax there that has been introduced in PHP 5.4 (maaany years ago). (Source: http://docs.php.net/manual/en/language.types.array.php example 7).

That means you must be using PHP 5.3 or even older. I strongly recommend you to update to a newer version like 5.6 at least. Migrating to 7.0 can be a bit tricky, because XAseco will stop working (there are some fixes for that on tm forum).

However, my recommended solution for you: update to PHP 5.6.

EDIT: I just read [here](http://tm-forum.com/viewtopic.php?f=127&t=37120) that 5.6 can also be difficult. If you are running a production server in a datacenter, I'd urge you to update to PHP 7.x. If it's just a server you have at home and start now and then, just go with PHP 5.5

EDIT 2: if you decide to go with php 7.x, see [this](http://tm-forum.com/viewtopic.php?f=127&t=35817) and [this](http://tm-forum.com/viewtopic.php?f=127&t=37120)

**Comment by NoTimeToDrive** [comment] 2019-09-29 16:24
Thank you very much for info askuri.

That can be the problem.
Only...i use usbTMFserver_v2.9
It's a portable setup for server.
PHP include.
I'm not sure if i can update this :(

http://www.tm-forum.com/viewtopic.php?t=30001

Maybe i can ask inside TM-Forum for info

I'm sorry for this issues!!
I hope i can fix this.
Or i most use Win10 ;-)
Hope thats not needed!

I gone search a solution^^

EDIT:
Me also use autosave_1_tmf as name,
to store tracks on my server.
And not tracklist as you speak about in your tool.
That has no effects on what i do?

Thanks again and greetings ;-)

**Comment by askuri** [comment] 2019-09-29 16:29
If you can't find a solution on tm-forum, drop me a message at enwi2@t-online.de.
I can help you to fix that by email, closing here for now.

**Closed as completed by askuri** 2019-09-29 16:29 UTC
